# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=1000, verbose_name='Page URL')),
                ('raw_html', models.TextField(blank=True, verbose_name='Raw Html')),
                ('url_hash', models.CharField(blank=True, max_length=255, unique=True, verbose_name='URL Hash')),
                ('content_hash', models.CharField(blank=True, max_length=255, verbose_name='Content Hash')),
                ('status', models.SmallIntegerField(default=0, verbose_name='Request status')),
                ('content_type', models.CharField(blank=True, max_length=200, verbose_name='Response content type')),
                ('crawled', models.BooleanField(default=False, verbose_name='Successfully crawled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indexed', models.BooleanField(default=False, verbose_name='Successfully indexed')),
                ('in_links', models.ManyToManyField(blank=True, to='engine.WebPage')),
            ],
        ),
    ]
