# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='crawler_id',
            field=models.SmallIntegerField(choices=[[0, 'Main DB'], [1, 'Crawler 1'], [2, 'Crawler 2'], [3, 'Crawler 3'], [4, 'Crawler 4'], [5, 'Crawler 5'], [6, 'Crawler 6']], default=0),
        ),
    ]
