# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_remove_webpage_crawler_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='url_hash',
            field=models.CharField(blank=True, max_length=255, verbose_name='URL Hash'),
        ),
    ]
