# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_auto_20170410_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='url_hash',
            field=models.CharField(max_length=255, unique=True, verbose_name='URL Hash'),
        ),
    ]
